name: flakka_db
description: Persistent Data interface for the flakka object store
version: 0.1.0+1


environment:
  sdk: "^3.3.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ">=5.1.0 <7.0.0"
